Basic templates in python
scramjetorg/create-sequence pull request #1
Opened 2023-02-16 09:12 UTC by gzukowski

2023-02-16 16:12 UTC, a-tylenda commented on templates/js-function/package.json
> +  "name": "js-function",
```suggestion
  "name": "@scramjet/js-function",
```
Please apply this change `"name":` in each package.json file, thx 😉

2023-02-16 16:19 UTC, a-tylenda commented on templates/js-function/package.json
> +}
Please adjust each package.json content from js templates as it is in the js-simple template:

```suggestion
{
 {
  "name": "@scramjet/js-simple",
  "version": "1.0.0",
  "description": "Scramjet Cloud Platform Sequence Javascript Template",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "engines": {
    "node": ">=16"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/scramjetorg/create-sequence.git"
  },
  "bugs": {
    "url": "https://github.com/scramjetorg/create-sequence/issues"
  },
  "homepage": "https://github.com/scramjetorg/create-sequence#readme"
}
```

2023-02-17 08:51 UTC, alicja-gruzdz commented
@S4adam and @Tatarinho we need your help. Please take a look at the templates for Sequences in python and confirm that they would be supported by Python Runner and that they adhere to best python practices. Thanks!

2023-02-17 10:40 UTC, S4adam approved these changes
Exemplary! But perhaps we could create `requirements.txt` file for py-simple?

2023-02-23 08:19 UTC, alicja-gruzdz approved these changes

2023-02-23 11:27 UTC, ErykSol requested changes
Lot of inconsitency between languages and transform types.

2023-02-23 11:27 UTC, ErykSol commented on templates/ts-input/index.ts
> +import { ReadableApp  } from "@scramjet/types";
All ts templates should be the same code as js templates, but with added typescript types, otherwise it will confuse user.

2023-02-23 11:27 UTC, ErykSol commented on templates/py-input/main.py
> +from scramjet.streams import Stream
same as TS. Py examples should be same as those in js, so if we use streams in py than js shoud use streams, if we use generators js should use generators etc.

2023-02-23 11:27 UTC, ErykSol commented on templates/py-simple/main.py
> +		yield f"id:{id}"
does string conversion on returned value is really a simple template? Shouldn't that be just `yield id`

2023-02-24 10:26 UTC, MichalCz commented on templates/ts-output/package.json
> +  "dependencies":"" ,
```suggestion
  "dependencies": {},
```

2023-02-24 10:26 UTC, MichalCz commented on templates/ts-stream/package.json
> +  "dependencies":"" ,
```suggestion
  "dependencies": {},
```

2023-03-02 08:57 UTC, closed without merging