Consumer, generator and transformer template for all supported languages
scramjetorg/create-sequence pull request #8
Opened 2023-03-01 20:51 UTC by gzukowski

2023-03-08 09:12 UTC, ErykSol requested changes
Fix packing redundant devDependencies in ts samples

2023-03-08 09:12 UTC, ErykSol commented on templates/ts-consumer/package.json
> +    "predeploy" : "npm i && tsc -p tsconfig.json && cp -r package.json dist/ && mv node_modules dist"
this command will install all dependencies along with devDependencies, and move them to sequence package. Only dependencies should be added to sequence package. Proper command would be `tsc -p tsconfig.json && cp package.json dist/ && (cd dist && npm i --omit=dev)`

2023-03-08 09:12 UTC, ErykSol commented on templates/ts-generator/package.json
> +    "predeploy" : "npm i && tsc -p tsconfig.json && cp -r package.json dist/ && mv node_modules dist"
same case as in ts-consumer

2023-03-08 09:12 UTC, ErykSol commented on templates/ts-transformer/package.json
> +    "predeploy" : "npm i && tsc -p tsconfig.json && cp -r package.json dist/ && mv node_modules dist"
same case as in ts-consumer

2023-03-08 11:26 UTC, ErykSol commented
Remember to change:
https://github.com/scramjetorg/create-sequence/blob/da9c3735359946747f21f61db65b92a12288104c/create-sequence.js#L11
Otherwise scripts will stop working after changes.

2023-03-09 18:21 UTC, ErykSol commented on README.md
>  the main file and package.json file will be created out of `templates/default`.
templates/default no longer exist

2023-03-09 18:24 UTC, ErykSol commented on README.md
> +The command above will not create any sequence directory, main file and package.json will be created in a place from which `npm init ...` command was executed. We advise to create sequence directory
typo: main file->files (for TS and PY there is more)

2023-03-09 18:26 UTC, ErykSol commented on README.md
> +DEVELOPMENT=1 sth --runtime-adapter=process
not sure if DEVELOPMENT flag is required here.... please verify it not checked already

2023-03-09 18:32 UTC, ErykSol approved these changes
Looks good, small typos to fix, but scirpts looks fine :)

2023-03-10 11:30 UTC, a-tylenda approved these changes

2023-03-10 11:42 UTC, merged